### PR TITLE
Adding experimental macos support

### PR DESCRIPTION
**Pull request by deregtd**

### CODE REVIEW

**Comment by samcolby** [comment]
Hi, 

Thanks for this!  Do you work with @bjartebore et al?  

Is this to work with https://github.com/Microsoft/react-native-macos or https://github.com/ptmt/react-native-macos ?   I've no idea what the difference between the two is.

I'm quite happy to merge this, but I'm just worried about breaking the iphone integration as it is changing the same files and the xcodeproj.  I'll try and make some time to have a play with it.

Thanks
Sam

**Comment by deregtd** [comment]
Hello!  This is for the Microsoft version.  I haven't tried the ptmt one. :)

No rush!  I'm still experimenting as well, and I'm just using my fork for now, which unblocks me, so I'm just trying to be a good github citizen and send this back upstream!

Edit: no, I don't know @bjartebore

**Comment by samcolby** [comment]
Ah good stuff!  I'll see if I can get something working this weekend.

**Comment by deregtd** [comment]
@samcolby Hey.  I forgot that I had this PR open and my branch was auto committing to here.

I have several commits that improve UWP and add working MacOS on my branch.  If you have some time, maybe peruse them and see if they're all interesting to the master branch here, and I can prepare PRs for the individual areas that you'd like merged back?

https://github.com/deregtd/react-native-ms-adal/commits/master

**Pull request closed without merging**
