### PR TITLE
RN does not have the window.atob() required by parseJWT, since ADAL a…

### PR DESCRIPTION
**Pull request by bjartebore**
…llready provides us with userInfo we have not the need to parse the token. I also removed all Deferred usage for Promise's (this should not have any braking changes since they provide the same api '.then(onFulFilles, onRejected)' onProgress provided by Deferred is not used in any way. I deleted the utility.js since we do not have any dependencies to it anymore

### CODE REVIEW

**Comment by samcolby** [comment]
Hi bjartebore, 

I'm on holiday right now, so may not be that responsive...  and wont be able to test this for a week or so I'm afraid.

Just a couple of thoughts for now until I can get a better look at it as I'm not really sure what problem we're solving here and we could potentially be introducing bugs.

(btw I've not spent long looking at this, so please correct me if I'm missing something obvious. You probably have a better understanding of what's going on with this ADAL stuff than I do now anyway).

-  Is this PR mostly performance improvements?  Or is there something else going on? Does removing the UserInfo.fromJWT call improve performance up that much?

- Does the authResult.userInfo object contain all the same information as the JWTToken?  I'm not sure why they would default to using jwt first if it does. Or is it just a bug in MS's code?  See https://github.com/samcolby/react-native-ms-adal/blob/4ec06eaef225031426020f60710cd44c68fed4a3/msadal/AuthenticationResult.js#L25-L31

```js
if (jwtToken) {
    this.userInfo = UserInfo.fromJWT(jwtToken);
}

if (!this.userInfo) {
    this.userInfo = new UserInfo(authResult.userInfo);
}
```

- I guess linked to the above.  Are you sure we're not missing an edge case, see some of the comments in the utilities.js file for further info.

- Is [this line](https://github.com/samcolby/react-native-ms-adal/pull/5/files#diff-29091606396e80b090dbcf48633201dfL82) supposed to be deleted?

- Switching from Deferred to Promise seems like a good idea.  But wont these changes make it harder to resync back to Microsoft's cordova version if anything changes on their end?  It is always likely that something may break in the future and we'll need to resync this back to their version.

Think that's all for now. 
Sam

**Comment by bjartebore** [comment]
Hi and thanks for a good review :)

The main reason I removed the fromJWT method is due to the fact that react native (on ios) is not using this at all. It is dependent upon window.atob() for decoding base64 strings. atob() is for some reason only available when the debugger is connected, meaning that in every production build this will fail and fallback to the userInfo object provided by adal-objc. This did come clear to me while accessing the token cache directly to get user information for offline usage.

1. Not sure how much performance improvement we will gain, if the code was working it would be a bit of deserialization going on, but the impact is small depending on how often you ask for a token.

2. No, the main difference between the objc version and cordova version is how the userId is set.
 objc: [AdUserInformation.m](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/ADUserInformation.m#L180-L210)
js: [UserInfo.js](https://github.com/samcolby/react-native-ms-adal/blob/master/msadal/UserInfo.js#L64-L65)

3. Yes, the bride method does not expect this argument to exists and the method is therefore failing (should have been mentioned in the commit)

4. This is not a big thing for me, I think it unnecessary to ship a deferred library to a platform that has Promises. Today we have to wrap them to be fully ES6 Promise compatible, not really a big issue but a bit tedious.

**Comment by samcolby** [comment]
Hi, 

Good responses :)

I like the changes and don't mind merging them.  I guess my only issue is whether they are worth including given that it will make resyncing to the original cordova version more complicated. I'm not sure this is a huge problem, but it is something we need to consider.  

What do you think? 


And just so I'm clear.  Is the item.isMultipleResourceRefreshToken deletion part working correctly now? 

>>  Is [this line](https://github.com/samcolby/react-native-ms-adal/pull/5/files#diff-29091606396e80b090dbcf48633201dfL82) supposed to be deleted?

> Yes, the bride method does not expect this argument to exists and the method is therefore failing (should have been mentioned in the commit)

**Comment by bjartebore** [comment]
I *think* that when we want to sync something from the cordova project it's most likely the ios and  android code that has changed, the javascript api will most likely not change, this is ofc just guesses.

But if you are reluctant to change the from deferred to promises from deferreds I have no problem changing the commit to take this back :)

 when I remove the isMultipleResourceRefreshToken it is working correctly.

**Pull request merged**
